SELECT FIRST_NAME, LAST_NAME, HIRE_DATE from EMPLOYEES WHERE INSTR(UPPER(FIRST_NAME),'A')>0 AND INSTR(UPPER(FIRST_NAME),'N')<=0 OR HIRE_DATE>='01-July-1995';

SELECT SUBSTR(FIRST_NAME, 1, 1)||'.'||' '||LAST_NAME FULL_NAME, HIRE_DATE-TRUNC(HIRE_DATE, 'MONTH')+1 WORKING_DAYS_FIRST_MONTH FROM EMPLOYEES;

SELECT MANAGER_ID, COUNT(DISTINCT EMPLOYEE_ID) COUNT_MANAGED_EMPLOYEES, AVG(SALARY) FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID HAVING COUNT(DISTINCT EMPLOYEE_ID)>4 AND AVG(SALARY)>2000
ORDER BY COUNT_MANAGED_EMPLOYEES DESC, AVG(SALARY) ASC;

SELECT TO_CHAR(HIRE_DATE, 'YYYY') YEAR, JOB_ID, COUNT(DISTINCT EMPLOYEE_ID) TOTAL_HIRED, MAX(SALARY)-MIN(SALARY) DIFF_MAX_MIN FROM EMPLOYEES GROUP BY TO_CHAR(HIRE_DATE, 'YYYY'), JOB_ID;

SELECT COUNTRY_NAME, NVL(CNT3, 0) EMPLOYEES_WORKING FROM COUNTRIES LEFT JOIN
(SELECT COUNTRY_ID, SUM(CNT2) CNT3 FROM LOCATIONS LEFT JOIN
(SELECT LOCATION_ID, SUM(CNT) CNT2 FROM DEPARTMENTS LEFT JOIN (SELECT DEPARTMENT_ID, COUNT(DISTINCT EMPLOYEE_ID) CNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID) E ON 
(DEPARTMENTS.DEPARTMENT_ID=E.DEPARTMENT_ID) GROUP BY LOCATION_ID) D ON (LOCATIONS.LOCATION_ID=D.LOCATION_ID) GROUP BY COUNTRY_ID) L ON(COUNTRIES.COUNTRY_ID=L.COUNTRY_ID);

SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE ABS(SALARY-(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales'))) <= 5000;

SELECT E1.LAST_NAME, COUNT(DISTINCT E2.EMPLOYEE_ID) MORE_SALARY, COUNT(DISTINCT E3.EMPLOYEE_ID) LESS_SALARY FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON E2.SALARY > E1.SALARY LEFT JOIN EMPLOYEES E3 ON E3.SALARY < E1.SALARY GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME;

SELECT DISTINCT LOCATION_ID FROM LOCATIONS WHERE LOCATION_ID NOT IN (SELECT DISTINCT LOCATION_ID FROM DEPARTMENTS);