-- --------------- Basic sql (A2_setA) ---------------

SELECT SUBSTR(JOB_ID, 1, 1) FIRST_CHAR, AVG(MAX_SALARY) FROM JOBS GROUP BY SUBSTR(JOB_ID, 1, 1) ORDER BY FIRST_CHAR;
SELECT FIRST_NAME||' '||LAST_NAME FULL_NAME FROM EMPLOYEES WHERE LENGTH(FIRST_NAME||' '||LAST_NAME) > 10;
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID HAVING NVL(AVG(SALARY), 0) > 5000 AND NVL(AVG(SALARY), 200000) < 15000;
SELECT TO_CHAR(SYSDATE, 'MONTH'), COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'MONTH') = TO_CHAR(SYSDATE,'MONTH');
SELECT TO_CHAR(SYSDATE, 'MONTH'), COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'MONTH') = TO_CHAR(SYSDATE,'MONTH');
SELECT EMPLOYEE_ID, FIRST_NAME, (SALARY*12)*(1+COMMISSION_PCT) YEARLY_INCOME FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;



-- --------------- Advanced sql (Online2_setA) ---------------

SELECT E1.LAST_NAME, COUNT(DISTINCT E2.EMPLOYEE_ID) HIRED_BEFORE, COUNT(DISTINCT E3.EMPLOYEE_ID) HIRED_AFTER FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON E2.HIRE_DATE < E1.HIRE_DATE LEFT JOIN EMPLOYEES E3 ON E3.HIRE_DATE > E1.HIRE_DATE GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME;
SELECT LAST_NAME, SALARY FROM EMPLOYEES E1 WHERE 5 > (SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES E2 WHERE E2.SALARY > E1.SALARY);
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE ABS(SALARY-(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales'))) <= 5000;
SELECT * FROM EMPLOYEES E1 LEFT JOIN (SELECT DEPARTMENT_ID, AVG(SALARY) AVERAGE_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID) E2 ON (E1.DEPARTMENT_ID = E2.DEPARTMENT_ID) WHERE E1.SALARY > E2.AVERAGE_SALARY;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID NOT IN (SEECT DISTINCT MANAGER_ID FROM EMPLOYEES) AND EMPLOYEE_ID IN
(SELECT EMPLOYEE_ID FROM JOB_HISTORY WHERE JOB_ID IN
(SELECT JOB_ID FROM JOBS WHERE INSTR(UPPER(JOB_TITLE), 'MANAGER') > 0));